# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageConverter(object):
    def setupUi(self, ImageConverter):
        ImageConverter.setObjectName("ImageConverter")
        ImageConverter.resize(800, 694)
        self.centralwidget = QtWidgets.QWidget(ImageConverter)
        self.centralwidget.setObjectName("centralwidget")
        self.selectButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectButton.setGeometry(QtCore.QRect(0, 10, 791, 41))
        self.selectButton.setObjectName("selectButton")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 60, 791, 531))
        self.graphicsView.setObjectName("graphicsView")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(0, 600, 791, 31))
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setGeometry(QtCore.QRect(0, 640, 791, 41))
        self.saveButton.setObjectName("saveButton")
        ImageConverter.setCentralWidget(self.centralwidget)

        self.retranslateUi(ImageConverter)
        QtCore.QMetaObject.connectSlotsByName(ImageConverter)

    def retranslateUi(self, ImageConverter):
        _translate = QtCore.QCoreApplication.translate
        ImageConverter.setWindowTitle(_translate("ImageConverter", "Converter image"))
        self.selectButton.setText(_translate("ImageConverter", "Выберите изображение"))
        self.saveButton.setText(_translate("ImageConverter", "Сжать изображение "))
