# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alphabet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alphabet(object):
    def setupUi(self, Alphabet):
        Alphabet.setObjectName("Alphabet")
        Alphabet.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Alphabet)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 791, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.languageComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.languageComboBox.setObjectName("languageComboBox")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.verticalLayout.addWidget(self.languageComboBox)
        self.addAlphabetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addAlphabetButton.setObjectName("addAlphabetButton")
        self.verticalLayout.addWidget(self.addAlphabetButton)
        self.inTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.inTextEdit.setObjectName("inTextEdit")
        self.verticalLayout.addWidget(self.inTextEdit)
        self.inputButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.inputButton.setObjectName("inputButton")
        self.verticalLayout.addWidget(self.inputButton)
        self.outTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.outTextEdit.setObjectName("outTextEdit")
        self.verticalLayout.addWidget(self.outTextEdit)
        Alphabet.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Alphabet)
        self.statusbar.setObjectName("statusbar")
        Alphabet.setStatusBar(self.statusbar)

        self.retranslateUi(Alphabet)
        QtCore.QMetaObject.connectSlotsByName(Alphabet)

    def retranslateUi(self, Alphabet):
        _translate = QtCore.QCoreApplication.translate
        Alphabet.setWindowTitle(_translate("Alphabet", "Алфавит"))
        self.languageComboBox.setItemText(0, _translate("Alphabet", "Русский"))
        self.languageComboBox.setItemText(1, _translate("Alphabet", "Английский"))
        self.addAlphabetButton.setText(_translate("Alphabet", "Добавить алфавит"))
        self.inputButton.setText(_translate("Alphabet", "Ввести текст"))
